import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  authScreen: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(180deg, #fff7ed 0%, #ffe4c7 100%)",
    padding: 24,
    fontFamily: '"Segoe UI", sans-serif',
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    padding: 24,
    borderRadius: 24,
    background: "rgba(255,255,255,0.9)",
    border: "1px solid rgba(47, 27, 12, 0.12)",
    boxShadow: "0 10px 30px rgba(120, 53, 15, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  app: {
    minHeight: "100vh",
    padding: 24,
    background: "linear-gradient(180deg, #fff7ed 0%, #ffe4c7 100%)",
    color: "#2f1b0c",
    fontFamily: '"Segoe UI", sans-serif',
  },
  header: {
    marginBottom: 24,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  tabsRow: {
    display: "flex",
    gap: 10,
    marginBottom: 24,
    flexWrap: "wrap",
  },
  tabButton: {
    padding: "12px 18px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.14)",
    background: "#fffaf5",
    color: "#2f1b0c",
    fontWeight: 700,
    cursor: "pointer",
  },
  tabButtonActive: {
    background: "#2f1b0c",
    color: "#fff7ed",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 320px) minmax(420px, 1fr)",
    gap: 16,
    marginBottom: 24,
  },
  manualSection: {
    marginTop: 32,
  },
  alertBanner: {
    marginBottom: 16,
    padding: "14px 18px",
    borderRadius: 18,
    background: "#2f1b0c",
    color: "#fff7ed",
    boxShadow: "0 10px 30px rgba(120, 53, 15, 0.16)",
  },
  filtersBar: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1.4fr) minmax(160px, 0.8fr) minmax(160px, 0.8fr) auto",
    gap: 12,
    marginBottom: 24,
    alignItems: "end",
  },
  filterField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontWeight: 600,
  },
  clearFiltersButton: {
    height: 48,
    padding: "0 16px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.16)",
    background: "#fffaf5",
    color: "#2f1b0c",
    fontWeight: 700,
    cursor: "pointer",
  },
  summaryCard: {
    padding: 20,
    borderRadius: 24,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(47, 27, 12, 0.12)",
    boxShadow: "0 10px 30px rgba(120, 53, 15, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  settingsCard: {
    padding: 20,
    borderRadius: 24,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(47, 27, 12, 0.12)",
    boxShadow: "0 10px 30px rgba(120, 53, 15, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  configuratorCard: {
    padding: 16,
    borderRadius: 20,
    background: "#fffaf5",
    border: "1px solid rgba(47, 27, 12, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  optionGroups: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  optionGroupCard: {
    padding: 14,
    borderRadius: 16,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(47, 27, 12, 0.08)",
  },
  groupHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  optionList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  optionButton: {
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.12)",
    background: "#fff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    cursor: "pointer",
    color: "inherit",
    textAlign: "left",
  },
  optionButtonActive: {
    borderColor: "#c46a2d",
    background: "rgba(246, 182, 96, 0.18)",
  },
  errorBadge: {
    padding: "6px 10px",
    borderRadius: 999,
    background: "#7f1d1d",
    color: "#fff",
    fontSize: 12,
  },
  eyebrow: {
    margin: 0,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: "#92400e",
  },
  title: {
    margin: "8px 0",
    fontSize: 40,
  },
  sectionTitle: {
    margin: "6px 0 0",
    fontSize: 22,
  },
  copy: {
    margin: 0,
    color: "#6b4a33",
  },
  summaryValue: {
    fontSize: 34,
    fontWeight: 800,
  },
  metricRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "#6b4a33",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontWeight: 600,
  },
  inlineFields: {
    display: "grid",
    gridTemplateColumns: "1fr 120px",
    gap: 12,
  },
  input: {
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.16)",
    background: "#fffaf5",
    font: "inherit",
    color: "inherit",
  },
  textarea: {
    minHeight: 420,
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.16)",
    background: "#fffaf5",
    font: '13px "Cascadia Code", Consolas, monospace',
    color: "inherit",
    resize: "vertical",
  },
  multiSelect: {
    minHeight: 120,
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.16)",
    background: "#fffaf5",
    font: "inherit",
    color: "inherit",
  },
  catalogSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    paddingTop: 8,
  },
  catalogList: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  catalogCard: {
    padding: 16,
    borderRadius: 18,
    background: "#fffaf5",
    border: "1px solid rgba(47, 27, 12, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  catalogNestedHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  catalogNestedList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  catalogNestedCard: {
    padding: 12,
    borderRadius: 14,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(47, 27, 12, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  catalogRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "end",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 600,
  },
  secondaryButton: {
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.12)",
    background: "#fffaf5",
    color: "inherit",
    fontWeight: 700,
    cursor: "pointer",
  },
  draftList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 72,
  },
  draftItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 16,
    background: "#fffaf5",
    border: "1px solid rgba(47, 27, 12, 0.08)",
  },
  removeButton: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "none",
    background: "#7f1d1d",
    color: "#fff7ed",
    cursor: "pointer",
  },
  successText: {
    margin: 0,
    color: "#166534",
    fontWeight: 700,
  },
  warningText: {
    margin: 0,
    color: "#9a3412",
    fontWeight: 700,
  },
  validationCard: {
    padding: 16,
    borderRadius: 18,
    background: "#fff7ed",
    border: "1px solid rgba(154, 52, 18, 0.18)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  validationList: {
    margin: 0,
    paddingLeft: 18,
    color: "#7c2d12",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  authError: {
    margin: 0,
    color: "#991b1b",
    fontWeight: 700,
  },
  emptyCard: {
    padding: 24,
    borderRadius: 24,
    background: "rgba(255,255,255,0.82)",
    border: "1px solid rgba(47, 27, 12, 0.12)",
    marginBottom: 24,
  },
  emptyText: {
    color: "#6b4a33",
  },
  ordersSection: {
    marginTop: 24,
  },
  sectionHeading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    gap: 16,
  },
  sectionCount: {
    minWidth: 52,
    height: 52,
    borderRadius: 16,
    background: "#2f1b0c",
    color: "#fff7ed",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    fontWeight: 800,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 16,
  },
  card: {
    padding: 20,
    borderRadius: 24,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(47, 27, 12, 0.12)",
    boxShadow: "0 10px 30px rgba(120, 53, 15, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  cardMeta: {
    margin: "6px 0 0",
    color: "#6b4a33",
    fontSize: 13,
  },
  statusBadge: {
    padding: "8px 12px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 700,
  },
  itemsList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  itemCard: {
    padding: 14,
    borderRadius: 16,
    background: "#fffaf5",
    border: "1px solid rgba(47, 27, 12, 0.08)",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
  },
  modifierText: {
    marginTop: 6,
    color: "#6b4a33",
    fontSize: 14,
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  cardActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  totalValue: {
    fontSize: 28,
  },
  printButton: {
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid rgba(47, 27, 12, 0.16)",
    background: "#fffaf5",
    color: "#2f1b0c",
    fontWeight: 700,
    cursor: "pointer",
  },
  actionButton: {
    padding: "12px 16px",
    borderRadius: 14,
    border: "none",
    background: "#ea580c",
    color: "#fff7ed",
    fontWeight: 700,
    cursor: "pointer",
  },
  buttonDisabled: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  readyText: {
    color: "#166534",
    fontWeight: 700,
  },
};
