import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "240px 1.2fr 1fr",
    background:
      "linear-gradient(135deg, rgba(245, 235, 220, 1) 0%, rgba(255, 250, 244, 1) 50%, rgba(238, 220, 195, 1) 100%)",
    color: "#2d1606",
    fontFamily: '"Segoe UI", sans-serif',
  },
  appStacked: {
    gridTemplateColumns: "1fr",
  },
  appMobile: {
    minHeight: "auto",
  },
  sidebar: {
    padding: 24,
    borderRight: "1px solid rgba(45, 22, 6, 0.12)",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    background: "rgba(120, 53, 15, 0.08)",
  },
  sidebarStacked: {
    borderRight: "none",
    borderBottom: "1px solid rgba(45, 22, 6, 0.12)",
  },
  sidebarMobile: {
    padding: 18,
  },
  eyebrow: {
    margin: 0,
    fontSize: 12,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#8a4b21",
  },
  title: {
    margin: "8px 0",
    fontSize: 34,
    lineHeight: 1.05,
  },
  copy: {
    margin: 0,
    color: "#6b4a33",
    lineHeight: 1.5,
  },
  categoryList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  categoryListInline: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  categoryButton: {
    padding: "16px 18px",
    borderRadius: 16,
    border: "1px solid rgba(45, 22, 6, 0.12)",
    background: "rgba(255, 255, 255, 0.72)",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left",
    fontSize: 16,
  },
  categoryButtonInline: {
    flex: "1 1 160px",
  },
  categoryButtonActive: {
    background: "#2d1606",
    color: "#fff6eb",
  },
  menuPanel: {
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  menuPanelMobile: {
    padding: 18,
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    margin: "6px 0 0",
    fontSize: 28,
  },
  productGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
    alignContent: "start",
  },
  productCard: {
    minHeight: 180,
    padding: 20,
    borderRadius: 24,
    border: "1px solid rgba(45, 22, 6, 0.12)",
    background: "rgba(255, 255, 255, 0.88)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
    boxShadow: "0 10px 30px rgba(75, 43, 18, 0.08)",
  },
  productCardActive: {
    outline: "3px solid #c46a2d",
    transform: "translateY(-2px)",
  },
  productTitle: {
    margin: "0 0 8px",
    fontSize: 20,
  },
  productDescription: {
    margin: 0,
    color: "#6b4a33",
    lineHeight: 1.5,
  },
  detailPanel: {
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    borderLeft: "1px solid rgba(45, 22, 6, 0.12)",
    background: "rgba(255, 252, 247, 0.82)",
  },
  detailPanelStacked: {
    borderLeft: "none",
    borderTop: "1px solid rgba(45, 22, 6, 0.12)",
  },
  detailPanelMobile: {
    padding: 18,
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  modifierStack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  groupCard: {
    padding: 16,
    borderRadius: 20,
    background: "rgba(255, 255, 255, 0.9)",
    border: "1px solid rgba(45, 22, 6, 0.12)",
  },
  groupHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 12,
  },
  groupTitle: {
    fontSize: 16,
    margin: 0,
  },
  groupHint: {
    margin: "4px 0 0",
    color: "#6b4a33",
    fontSize: 14,
  },
  errorBadge: {
    padding: "6px 10px",
    borderRadius: 999,
    background: "#7f1d1d",
    color: "#fff",
    fontSize: 12,
  },
  optionList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  optionButton: {
    padding: "14px 16px",
    borderRadius: 16,
    border: "1px solid rgba(45, 22, 6, 0.12)",
    background: "#fff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    textAlign: "left",
    cursor: "pointer",
    color: "inherit",
  },
  optionButtonActive: {
    borderColor: "#c46a2d",
    background: "rgba(246, 182, 96, 0.18)",
  },
  optionMeta: {
    margin: "4px 0 0",
    color: "#6b4a33",
    fontSize: 13,
  },
  summaryCard: {
    padding: 18,
    borderRadius: 20,
    background: "#2d1606",
    color: "#fff6eb",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  confirmBanner: {
    padding: "12px 14px",
    borderRadius: 14,
    background: "rgba(255, 246, 235, 0.14)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  quantityRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quantityControl: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  qtyButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: "none",
    background: "#fff6eb",
    color: "#2d1606",
    cursor: "pointer",
    fontSize: 20,
  },
  quantityValue: {
    minWidth: 24,
    textAlign: "center",
    fontWeight: 700,
  },
  selectedSummary: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
  },
  footerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  totalValue: {
    fontSize: 28,
  },
  addButton: {
    padding: "14px 18px",
    borderRadius: 14,
    border: "none",
    background: "#f59e0b",
    color: "#2d1606",
    fontWeight: 700,
    cursor: "pointer",
  },
  addButtonDisabled: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  cartCard: {
    padding: 18,
    borderRadius: 20,
    background: "rgba(255, 255, 255, 0.9)",
    border: "1px solid rgba(45, 22, 6, 0.12)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  cartBadge: {
    minWidth: 72,
    padding: "10px 12px",
    borderRadius: 14,
    background: "#2d1606",
    color: "#fff6eb",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  cartList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  cartItem: {
    paddingTop: 12,
    borderTop: "1px solid rgba(45, 22, 6, 0.12)",
  },
  cartModifier: {
    marginTop: 6,
    color: "#6b4a33",
    fontSize: 14,
  },
  submitMessage: {
    margin: 0,
    color: "#166534",
    fontWeight: 600,
  },
  successCard: {
    padding: "12px 14px",
    borderRadius: 14,
    background: "rgba(22, 101, 52, 0.08)",
    color: "#166534",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  trackingCard: {
    padding: "14px",
    borderRadius: 16,
    background: "rgba(45, 22, 6, 0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  trackingTitle: {
    fontSize: 18,
  },
  trackingStatus: {
    fontSize: 24,
    fontWeight: 800,
    color: "#2d1606",
  },
  trackingCopy: {
    margin: 0,
    color: "#6b4a33",
    lineHeight: 1.5,
  },
  cartHelpText: {
    margin: 0,
    color: "#6b4a33",
    fontSize: 14,
  },
  submitOrderButton: {
    padding: "14px 18px",
    borderRadius: 14,
    border: "none",
    background: "#2d1606",
    color: "#fff6eb",
    fontWeight: 700,
    cursor: "pointer",
  },
  ticketFooterText: {
    margin: 0,
    color: "#8a4b21",
    fontSize: 13,
    textAlign: "center",
  },
  emptyText: {
    margin: 0,
    color: "#6b4a33",
    lineHeight: 1.5,
  },
};
